---
# tasks file for node_exporter
- name: Download and unarchive node_exporter into temporary location.
  unarchive:
    src: "{{ node_exporter_download_url }}"
    dest: /tmp
    remote_src: true
    mode: 0755
  register: node_exporter_download_check

- name: Move node_exporter binary into place.
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ node_exporter_arch }}/node_exporter"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: true
  notify: restart node_exporter
  when: >
    node_exporter_download_check is changed

- name: Create node_exporter user.
  user:
    name: node_exporter
    shell: /sbin/nologin
    state: present

- name: Deploy node_exporter
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/node_exporter.service"
    mode: '0644'
    backup: yes

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart node_exporter

- name: Collect facts about system services
  service:
      name: node_exporter
      state: "started"
      enabled: "true"

- name: Deploy node_exporter to consul
  template:
    src: node_exporter.json.j2
    dest: "{{ consul_conf_dir }}node_exporter.json"
    mode: '0644'
    backup: yes

- name: Reload consul
  command: consul reload
  become: true