---
# tasks file for nginx_exporter
- name: Download and unarchive nginx_exporter into temporary location.
  unarchive:
    src: "{{ nginx_exporter_download_url }}"
    dest: /tmp
    remote_src: true
    mode: 0755
  register: nginx_exporter_download_check

- name: Move nginx_exporter binary into place.
  copy:
    src: "/tmp/nginx-prometheus-exporter"
    dest: /usr/local/bin/
    mode: 0755
    remote_src: true
  notify: restart nginx_exporter
#  when: >
#    nginx_exporter_download_check is changed

- name: Create nginx_exporter user.
  user:
    name: nginx_exporter
    shell: /sbin/nologin
    state: present

- name: Deploy nginx_exporter
  template:
    src: nginx_exporter.service.j2
    dest: "/etc/systemd/system/nginx_exporter.service"
    mode: '0644'
    backup: yes

- name: Reload systemd daemon if unit file is changed.
  systemd:
    daemon_reload: true
  notify: restart nginx_exporter

- name: Collect facts about system services
  service:
      name: nginx_exporter
      state: "started"
      enabled: "true"
  notify: restart nginx

- name: Deploy nginx_stats.conf
  template:
    src: stats.conf.j2
    dest: "/etc/nginx/conf.d/stats.conf"
    mode: '0644'
    backup: yes

- name: Deploy nginx_exporter to consul
  template:
    src: nginx_exporter.json.j2
    dest: "{{ consul_conf_dir }}nginx_exporter.json"
    mode: '0644'
    backup: yes

- name: Reload consul
  command: consul reload
  become: true