---
# tasks file for nginx
- block:
  - name: Install nginx package от RedHat
    yum:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install nginx package on debian systems
    apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"

  - name: Ensure nginx is enabled and running
    service:
      name: nginx
      state: started
      enabled: true
  
  - name: Modding index.html
    shell: sed -i 's/Welcome to nginx!/Welcome to "{{ server_name }}"/' /usr/share/nginx/html/index.html

  - name: Disable default site if required
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    when: not nginx_default_sites_enabled

  - name: Add a user to a password file and ensure permissions are set
    vars:
      keys: "{{ lookup('hashi_vault', 'secret={{ vault_keys_path }} token=$vault_token url={{ vault_server }}')}}"
    community.general.htpasswd:
      path: /etc/nginx/passwdfile
      name: "{{ item.key }}"
      password: "{{ item.value }}"
      owner: root
      group: www-data
      mode: 0640
    with_items:
        - "{{ keys | dict2items }}"

  - name: Deploy nginx site file
    template:
      src: site.conf.j2
      dest: "{{ nginx_path }}/conf.d/site.conf"
      owner: root
      group: root
      mode: '0644'
      backup: yes

  - name: Deploy nginx configuration file
    template:
      src: nginx.conf.j2
      dest: "{{ nginx_conf_path }}"
      owner: root
      group: root
      mode: '0644'
      backup: yes
    notify:
      - Reload nginx

  become: true