---
# tasks file for docker

- block:

  - name: installation env
    apt:
      name: ca-certificates, curl
      state: present
      update_cache: yes

  - name: keyrings
    shell: install -m 0755 -d /etc/apt/keyrings

  - name: add GPG
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add the repository to Apt sources 
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present
      filename: docker
  
  - name: update cache
    apt:
      update_cache: yes

  - name: install docker
    apt:
      name: docker-ce, docker-ce-cli, containerd.io, docker-buildx-plugin, docker-compose-plugin
      state: present

  - name: service docker
    service:
      name: docker
      state: started
      enabled: yes
  
  - name: adding ansible user to group docker
    user:
      name: '{{ ansible_user_id }}'
      groups: docker
      append: yes
  
  - name: Install Docker Compose
    get_url:
      url: https://github.com/docker/compose/releases/download/{{ DockerComposeVersion }}/docker-compose-linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: u+x,g+x,o+x
  
  become: true