---
# tasks file for common

- name: set timezone (see defaults)
  timezone:
    name: "{{ time_zone }}"

- name: "Ansible | Print a variable"
  debug:
    msg: "The new hostname is: {{ inventory_hostname }}"

- name: Set a hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: update apt cache
  apt:
    update_cache: yes
  become: true

- block:
    - name: "DEBUG | Print a variable - path for swap"
      debug:
        msg: "The path for swap: {{ swapfile_path }}"

    - name: create a swap file
      shell: fallocate -l {{ swap_size }} {{ swapfile_path }}
      args:
        creates: "{{ swapfile_path }}"
      become: true

    - name: set the correct permissions
      file:
        path: "{{ swapfile_path }}"
        owner: root
        group: root
        mode: '0600'
      become: true

    - name: make the file a swap file
      shell: mkswap {{ swapfile_path }}
      when: ansible_facts.swapfree_mb == 0
      become: true

    - name: enable the swap file
      shell: swapon {{ swapfile_path }}
      when: ansible_facts.swapfree_mb == 0
      become: true

    - name: add swap file to fstab
      mount:
        name: none
        src: "{{ swapfile_path }}"
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present
      become: true