---
# tasks file for common

- name: Set timezone (see defaults)
  timezone:
    name: "{{ time_zone }}"

- name: "Ansible | Print a variable"
  debug:
    msg: "The new hostname is: {{ inventory_hostname  }}"

- name: Set a hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Update apt cache
  apt:
    update_cache: yes
  become: true

- name: Get swap path
  shell: swapon --show
  register: swap_path

- name: Pring swap path
  debug:
    var: swap_path.stdout_lines

- name: Get LA
  shell: uptime | cut -d ' ' -f 11-
  register: host_LA

- name: Pring LA
  debug:
    var: host_LA.stdout

- block:
    - name: "DEBUG | Print a variable - path for swap"
      debug:
        msg: "The path for swap: {{ swapfile_path }}"

    - name: Create a swap file
      shell: fallocate -l {{ swap_size }} {{ swapfile_path }}
      args:
        creates: "{{ swapfile_path }}"

    - name: Set the correct permissions
      file:
        path: "{{ swapfile_path }}"
        owner: root
        group: root
        mode: '0600'

    - name: Make the file a swap file
      shell: mkswap {{ swapfile_path }}
      when: ansible_facts.swapfree_mb == 0

    - name: Enable the swap file
      shell: swapon {{ swapfile_path }}
      when: ansible_facts.swapfree_mb == 0

    - name: Add swap file to fstab
      mount:
        name: none
        src: "{{ swapfile_path }}"
        fstype: swap
        opts: sw
        passno: 0
        dump: 0
        state: present
    
  become: true

- name: Installation packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ packages }}"
  become: true