---
# tasks file for create_user72
- name: Add the user 'james' with a bash shell, appending the group 'admins' and 'developers' to the user's groups
  ansible.builtin.user:
    name: {{ new_user }}
    shell: /bin/bash

- name: Create a 2048-bit SSH key for user
  ansible.builtin.user:
    name: {{ new_user }}
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa