---
# tasks file for consul_agent
- name: Download consul
  get_url:
    url: "{{ consul_agent_url }}"
    dest: /tmp/consul.zip

- name: Extract consul
  unarchive:
    src:  /tmp/consul.zip
    dest: /tmp
    remote_src: yes

- name: Copy consul
  command: mv /tmp/consul /usr/local/bin/
  become: true

- name: Create a config directory if it does not exist
  file:
    path: /etc/consul.d
    state: directory
    mode: '0755'

- name: Deploy consul config
  template:
    src: consul.hcl.j2
    dest: "/etc/consul.d/consul.hcl"
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Deploy consul service
  template:
    src: consul.service.j2
    dest: "/etc/systemd/system/consul.service"
    owner: root
    group: root
    mode: '0644'
    backup: yes

- block:
  - name: Daemon-reload
    command: systemctl daemon-reload

  - name: Enable service consul
    ansible.builtin.service:
      name: consul
      enabled: yes

  - name: Start service consul, if not started
    ansible.builtin.service:
      name: consul
      state: restarted
  
  - name: Collect facts about system services
    systemd:
      name: "consul"
    register: services_state
  
  - name: Debug
    debug:
      var: services_state.status.ActiveState
  
  become: true