---
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
      VAULT_ADDRESS: "http://0.0.0.0:8200"
    ports:
      - "8200:8200"
    volumes:
      - ${PWD}/file:/vault/file
      - ${PWD}/config.hcl:/vault/config/config.hcl
    command: server
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.hcl